# Generated by Django 3.0.5 on 2020-04-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boards', models.CharField(default='', max_length=100000)),
                ('userid', models.IntegerField(blank=True, default=0, null=True)),
                ('followers', models.CharField(default='', max_length=100000)),
                ('following', models.CharField(default='', max_length=100000)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='userid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
