# Generated by Django 3.0.5 on 2020-05-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200504_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.CharField(default='{"followers": []}', max_length=100000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='following',
            field=models.CharField(default='{"following": []}', max_length=100000),
        ),
    ]
