# Generated by Django 3.0.5 on 2020-05-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200504_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
