# Generated by Django 3.0.5 on 2020-05-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_board_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='username',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
